--CREATE Database ELECTRONICA
USE ELECTRONICA

CREATE TABLE CATEGORIA 
(
	CategoriaID SMALLINT NOT NULL IDENTITY(1,1),
	Descripcion VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (CategoriaID),
	CONSTRAINT CK_DescripcionCategoria CHECK (RTRIM(LTRIM(Descripcion)) <> '')	
)

CREATE TABLE PRODUCTO
(
	CodigoProducto INT NOT NULL IDENTITY(1,1),
	CategoriaID SMALLINT NOT NULL,
	Descripcion VARCHAR(50)	NOT NULL,
	PrecioUnitario MONEY NOT NULL,
	UnidadesDisponibles SMALLINT NOT NULL DEFAULT 0,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (CodigoProducto),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY (CategoriaID) REFERENCES CATEGORIA(CategoriaID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT CK_DescripcionProducto CHECK (RTRIM(LTRIM(Descripcion)) <> ''),
	CONSTRAINT CK_UnidadesDisponibles CHECK (UnidadesDisponibles >= 0)
)

CREATE TABLE VENDEDOR
(
	VendedorID TINYINT NOT NULL IDENTITY(1,1),
	Nombre VARCHAR(25) NOT NULL,
	ApellidoPaterno VARCHAR(25) NOT NULL,
	ApellidoMaterno VARCHAR(25) NOT NULL,
	NombreCompleto AS Nombre + ' ' + ApellidoPaterno + ' ' + ApellidoMaterno,
	CONSTRAINT PK_VENDEDOR PRIMARY KEY (VendedorID),
	CONSTRAINT CK_Nombre CHECK  (RTRIM(LTRIM(Nombre)) <> ''),
	CONSTRAINT CK_ApellidoP CHECK  (RTRIM(LTRIM(ApellidoPaterno)) <> ''),
	CONSTRAINT CK_ApellidoM CHECK  (RTRIM(LTRIM(ApellidoMaterno)) <> '')
)

CREATE TABLE VENTA
(
	VentaID INT NOT NULL IDENTITY(1,1),
	VendedorID TINYINT NOT NULL,
	FechaHora DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_VENTA PRIMARY KEY (VentaID),
	CONSTRAINT FK_VENDEDOR FOREIGN KEY (VendedorID) REFERENCES VENDEDOR(VendedorID) ON DELETE NO ACTION ON UPDATE CASCADE,
)

CREATE TABLE DETALLES_VENTAS
(
	VentaID INT NOT NULL,
	CodigoProducto INT NOT NULL,
	PrecioUnitario MONEY NOT NULL,
	UnidadesPedidas  SMALLINT NOT NULL DEFAULT 0,
	CONSTRAINT FK_VENTA FOREIGN KEY (VentaID) REFERENCES VENTA(VentaID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUCTO FOREIGN KEY (CodigoProducto) REFERENCES PRODUCTO(CodigoProducto) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT PK_DETALLES_VENTAS PRIMARY KEY	(VentaID, CodigoProducto),
	CONSTRAINT CK_UnidadesPedidas CHECK (UnidadesPedidas >= 0)
)

CREATE TABLE GASTO
(
	GastoID INT NOT NULL IDENTITY(1,1),
	Monto MONEY NOT NULL,
	FechaHora DATETIME NOT NULL DEFAULT GETDATE(),
	Descripcion VARCHAR(50)	NOT NULL,
	CONSTRAINT PK_GASTO PRIMARY KEY (GastoID),
	CONSTRAINT CK_DescripcionGasto CHECK (RTRIM(LTRIM(Descripcion)) <> '')
)


CREATE TABLE PAQUETE
(
	PaqueteID INT NOT NULL IDENTITY(1,1),	
	Descripcion VARCHAR(50)	NOT NULL DEFAULT '',
	FechaHora  DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT PK_PAQUETE PRIMARY KEY (PaqueteID)
)

CREATE TABLE PAQUETE_PRODUCTO
(
	PaqueteID INT NOT NULL,
	CodigoProducto INT NOT NULL,		
	CONSTRAINT FK_PAQUETEPRODUCTO_PAQUETE FOREIGN KEY (CodigoProducto) REFERENCES PRODUCTO(CodigoProducto) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT FK_PAQUETEPRODUCTO_PRODUCTO FOREIGN KEY (PaqueteID) REFERENCES PAQUETE(PaqueteID) ON DELETE NO ACTION ON UPDATE CASCADE,
	CONSTRAINT PK_PAQUETE_PRODUCTO PRIMARY KEY (PaqueteID, CodigoProducto)
)

CREATE TABLE PEDIDO
(
	PedidoID INT NOT NULL IDENTITY(1,1),
	FechaLlegada DATETIME NOT NULL,
	NumeroDeFactura VARCHAR(25) NOT NULL,
	Provedor VARCHAR(60) NOT NULL,
	Subtotal MONEY NOT NULL,
	IVA TINYINT NOT NULL,
	NumeroCheque VARCHAR(6) NOT NULL,
	FechaDeposito DATETIME NOT NULL
	CONSTRAINT PK_PEDIDO PRIMARY KEY(PedidoID)
)
